global.playerName = "Nick";
room_goto(rm_mine_entrance);
instance_create_layer(2, 224, "Instances", obj_player);
instance_create_layer(16, 16, "Instances", obj_player);
obj_player.sprite_index = spr_player_falling_coat_left;
instance_create_layer(2, 224, "Instances", obj_kat);
obj_kat.x = 160;
obj_kat.y = 2;
instance_create_layer(2, 224, "Instances", obj_bubble);
obj_bubble.image_index = 4;
obj_bubble.image_speed = 0;
obj_bubble.x = 191;
obj_bubble.y = 30;
obj_kat.sprite_index = spr_kat_fall;
global.canPause = false;
obj_player.canMove = false;
